
package jet.webservice.test.jaxws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Hello", targetNamespace = "http://webservice.jet/")
public interface Hello {


    /**
     * 
     * @param arg0
     * @return
     *     returns jet.webservice.test.jaxws.Response
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://webservice.jet/", className = "jet.webservice.test.jaxws.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webservice.jet/", className = "jet.webservice.test.jaxws.QueryResponse")
    public Response query(
        @WebParam(name = "arg0", targetNamespace = "")
        Request arg0);

}
